name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build Quarkus Native Image
        run: |
          # Budowanie aplikacji Quarkus Native Image
          ./mvnw package -Pnative -Dquarkus.native.container-build=true

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build Docker Image
        run: |
          # Zbuduj obraz Dockerowy
          docker build -t your-gh-username/your-repo-name:latest .

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker tag janicki-piotr/mikrus-service:latest ghcr.io/janicki-piotr/mikrus-service:latest
          docker push ghcr.io/janicki-piotr/mikrus-service:latest
