name: Build and deploy Mikrus API service
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  build:
    name: Build Native Quarkus
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm' # See 'Options' for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Native Quarkus
        run: ./gradlew build -Dquarkus.package.type=native -DskipTests
      - name: Change directory
        run: cd build
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
         host: ${{ secrets.SSH_SERVER }}
         username: ${{ secrets.SSH_LOGIN }}
         password: ${{ secrets.SSH_PASSWORD }}
         port: ${{ secrets.SSH_PORT }}
         source: "mikrus-service-0.1-runner"
         target: /home/mikrus-service
