name: Generate Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  build:
    name: Build Native Quarkus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true
#       - name: Build Native Quarkus
#         run: ./gradlew build -Dquarkus.package.type=native -DskipTests
      - run : touch test.txt
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
         host: ${{ secrets.SSH_SERVER }}
         username: ${{ secrets.SSH_LOGIN }}
         password: ${{ secrets.SSH_PASSWORD }}
         port: ${{ secrets.SSH_PORT }}
         source: "test.txt"
         target: /home
